# fly.toml file generated for wine-cellar

app = "wine-cellar"
primary_region = "ord" # San Jose, California
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PORT = "3000"
  CLOJURE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.http_checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  restart_limit = 0
  method = "get"
  path = "/health"
  protocol = "http"

